### PR TITLE
Scope down time sensitive code.

### LINKED ISSUE #67: Flaky test: TestTailFuzz
This test failed during presubmit, and it's unrelated to my PR (which was documentation only): https://travis-ci.com/Stackdriver/stackdriver-prometheus-sidecar/builds/94064905

@fabxc how can we investigate this?

### PR DESCRIPTION
**Pull request by jkohen**
The intention is to reduce flakes in this test. The test now will block until the 50,000 expected records are processed. Then it will wait for a second for potential extra records; because none are expected, there should be on flakes when the code is operating correctly.

Fixes #67

### CODE REVIEW

File: tail/tail_test.go [hunk 1]
```diff
@@ -85,6 +85,19 @@ func TestTailFuzz(t *testing.T) {
...
 		}
 	}
+	// Attempt to read one more record, but expect no more records.
+	// Give the reader a chance to run for a while, then cancel its
+	// context so the test doesn't time out.
+	go func() {
+		time.Sleep(time.Second)
+		cancel()
+	}()
+	if wr.Next() {
```
Comment (StevenYCChou) [inline tail/tail_test.go]: if the previous condition `wr.Next()` returns `false` for loop in line 74, this wr.Next() must not run based on the description of [wal.Reader.Next()](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/abebfbf954b702a77bfc73f4c833298e38e849ad/vendor/github.com/prometheus/tsdb/wal/wal.go#L685-L687).

Comment (jkohen) [reply tail/tail_test.go]: True. But if `wr.Next()` had returned `false`, the test should have aborted with a Fatal error above where the length of the read and write arrays are compared, right?

Comment (StevenYCChou) [reply tail/tail_test.go]: If wr.Next() in line 74 had returned `false` because internal read returns `io.EOF` ([code](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/abebfbf954b702a77bfc73f4c833298e38e849ad/vendor/github.com/prometheus/tsdb/wal/wal.go#L689-L691)), `wr.Err()` in line 77 would return `nil`, so it would not abort.

Comment (jkohen) [reply tail/tail_test.go]: Wouldn't it abort on line 80?

File: tail/tail_test.go [hunk 2]
```diff
@@ -65,13 +65,13 @@ func TestTailFuzz(t *testing.T) {
...
 		}
-		time.Sleep(time.Second)
-		cancel()
 	}()
 
 	wr := wal.NewReader(rc)
 
-	for wr.Next() {
+	// Expect `count` records; read them all, if possible. The test will
+	// time out if fewer records show up.
```
Comment (StevenYCChou) [inline tail/tail_test.go]: Wording suggestion: `The test will time out if fewer records show up` -> `The test will time out if fewer records show up AND [timeout](https://golang.org/cmd/go/#hdr-Testing_flags) flag is not disabled.`

An alternative is to add timer within this test case, so this test case does not rely on `timeout` flag.

Comment (jkohen) [reply tail/tail_test.go]: IMO, if someone disables the timer they get what they deserve (they should know what they're doing) :)

File: tail/tail_test.go (hunk 1 above)
Comment (jkohen) [reply tail/tail_test.go]: PTAL.

Comment (StevenYCChou) [reply tail/tail_test.go]: LGTM.
